-- Mark a category as a shared/global topic (custom quizzes searched-or-generated by
-- students). Shared categories are owned by the sentinel userId 'shared' and are served
-- to every student; auto-generated per-student categories keep isShared = 0.
ALTER TABLE `LearningCategory` ADD COLUMN `isShared` TINYINT(1) NOT NULL DEFAULT 0;
