CREATE TABLE `SkillScoreHistory` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `skillId` VARCHAR(191) NOT NULL,
  `score` DOUBLE NOT NULL,
  `confidence` DOUBLE NOT NULL,
  `source` VARCHAR(191) NOT NULL,
  `recordedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
