import { useState, type ReactNode } from 'react';
import { Check, X, ListChecks, Trophy, RotateCcw, FileQuestion } from 'lucide-react';
import type {
  RoadmapItemView,
  RoadmapTestSubmitResult,
  RoadmapTestView,
} from '@mentra/shared';
import { useRoadmapTopic, useStartTopicTest, useSubmitTopicTest } from '../../lib/roadmap.js';

type Mode = 'overview' | 'taking' | 'graded';

/**
 * The learning surface for a `topic` roadmap item: the full subtopic list (so the
 * student never has to wonder what to study) plus the completion test. Passing the
 * test is what marks the topic complete; subtopics and questions are generated by
 * the AI on demand server-side.
 */
export function RoadmapTopicPanel({ item }: { item: RoadmapItemView }) {
  const locked = item.status === 'locked';
  const { data: topic, isLoading } = useRoadmapTopic(item.id, !locked);
  const startTest = useStartTopicTest();
  const submitTest = useSubmitTopicTest();

  const [mode, setMode] = useState<Mode>('overview');
  const [test, setTest] = useState<RoadmapTestView | null>(null);
  const [answers, setAnswers] = useState<Record<string, number[]>>({});
  const [graded, setGraded] = useState<RoadmapTestSubmitResult | null>(null);

  if (locked) return null;

  const beginTest = () => {
    startTest.mutate(item.id, {
      onSuccess: (t) => {
        setTest(t);
        setAnswers({});
        setGraded(null);
        setMode('taking');
      },
    });
  };

  const toggle = (questionId: string, optionIndex: number, multi: boolean) => {
    setAnswers((prev) => {
      const cur = prev[questionId] ?? [];
      if (multi) {
        return {
          ...prev,
          [questionId]: cur.includes(optionIndex)
            ? cur.filter((i) => i !== optionIndex)
            : [...cur, optionIndex],
        };
      }
      return { ...prev, [questionId]: [optionIndex] };
    });
  };

  const submit = () => {
    if (!test) return;
    const payload = test.questions.map((q) => ({ questionId: q.id, selected: answers[q.id] ?? [] }));
    submitTest.mutate(
      { testId: test.id, answers: payload },
      {
        onSuccess: (res) => {
          setGraded(res);
          setMode('graded');
        },
      },
    );
  };

  if (isLoading) {
    return (
      <div className="mt-6 rounded-md bg-surface-sunken p-3 text-sm text-ink-muted ring-1 ring-border-subtle">
        Loading topic…
      </div>
    );
  }

  // --- Test in progress ---
  if (mode === 'taking' && test) {
    const allAnswered = test.questions.every((q) => (answers[q.id]?.length ?? 0) > 0);
    return (
      <div className="mt-6">
        <SectionTitle icon={FileQuestion}>
          Topic test · {test.questions.length} questions · pass at {test.passPercent}%
        </SectionTitle>
        <ol className="mt-3 space-y-4">
          {test.questions.map((q, i) => {
            const multi = q.type === 'multi_choice';
            const sel = answers[q.id] ?? [];
            return (
              <li key={q.id} className="rounded-md bg-surface-sunken p-3 ring-1 ring-border-subtle">
                <div className="flex gap-2 text-sm font-medium text-ink">
                  <span className="text-ink-faint">{i + 1}.</span>
                  <span>
                    {q.body}
                    {multi ? <span className="ml-1 text-xs text-ink-faint">(select all that apply)</span> : null}
                  </span>
                </div>
                <div className="mt-2 space-y-1.5">
                  {q.options.map((opt, oi) => {
                    const checked = sel.includes(oi);
                    return (
                      <button
                        type="button"
                        key={oi}
                        onClick={() => toggle(q.id, oi, multi)}
                        className={`flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-left text-sm ring-1 transition ${
                          checked
                            ? 'bg-surface-raised text-ink ring-border-strong'
                            : 'text-ink-muted ring-border-subtle hover:ring-border-strong'
                        }`}
                      >
                        <span
                          className={`grid size-4 shrink-0 place-items-center ${multi ? 'rounded-sm' : 'rounded-full'} ring-1 ${
                            checked ? 'bg-surface-inverse text-ink-inverse ring-transparent' : 'ring-border-strong'
                          }`}
                        >
                          {checked ? <Check className="size-3" /> : null}
                        </span>
                        {opt}
                      </button>
                    );
                  })}
                </div>
              </li>
            );
          })}
        </ol>
        <div className="mt-4 flex gap-2">
          <button
            type="button"
            onClick={() => setMode('overview')}
            className="h-11 rounded-md px-4 text-sm font-medium text-ink-muted ring-1 ring-border-subtle transition hover:ring-border-strong"
          >
            Cancel
          </button>
          <button
            type="button"
            disabled={!allAnswered || submitTest.isPending}
            onClick={submit}
            className="h-11 flex-1 rounded-md bg-surface-inverse text-sm font-semibold text-ink-inverse transition hover:bg-ink disabled:opacity-50"
          >
            {submitTest.isPending ? 'Submitting…' : allAnswered ? 'Submit test' : 'Answer every question to submit'}
          </button>
        </div>
      </div>
    );
  }

  // --- Graded result ---
  if (mode === 'graded' && graded && test) {
    const r = graded.result;
    return (
      <div className="mt-6">
        <div
          className={`rounded-md p-4 ring-1 ${
            r.passed ? 'bg-accent-green/10 ring-accent-green/30' : 'bg-surface-sunken ring-border-subtle'
          }`}
        >
          <div className="flex items-center gap-2">
            <Trophy className={`size-5 ${r.passed ? 'text-accent-green' : 'text-ink-faint'}`} />
            <span className="text-display-sm tracking-normal">{r.percent}%</span>
            <span className={`text-sm font-medium ${r.passed ? 'text-accent-green' : 'text-ink-muted'}`}>
              {r.passed ? 'Passed — topic complete' : `Not passed (need ${test.passPercent}%)`}
            </span>
          </div>
          <p className="mt-1 text-sm text-ink-muted">
            {r.score}/{r.maxScore} points · {r.correctCount}/{r.totalQuestions} correct · attempt {r.attemptNumber}
          </p>
        </div>

        <ol className="mt-4 space-y-3">
          {test.questions.map((q, i) => {
            const g = graded.graded.find((x) => x.questionId === q.id);
            const ok = g?.isCorrect ?? false;
            return (
              <li key={q.id} className="rounded-md bg-surface-sunken p-3 ring-1 ring-border-subtle">
                <div className="flex items-start gap-2 text-sm">
                  {ok ? (
                    <Check className="mt-0.5 size-4 shrink-0 text-accent-green" />
                  ) : (
                    <X className="mt-0.5 size-4 shrink-0 text-accent-red" />
                  )}
                  <span className="font-medium text-ink">
                    {i + 1}. {q.body}
                  </span>
                </div>
                <div className="mt-2 space-y-1">
                  {q.options.map((opt, oi) => {
                    const isCorrect = g?.correct.includes(oi);
                    const wasPicked = g?.selected.includes(oi);
                    return (
                      <div
                        key={oi}
                        className={`flex items-center gap-2 rounded-sm px-2 py-1 text-sm ${
                          isCorrect
                            ? 'text-accent-green'
                            : wasPicked
                              ? 'text-accent-red line-through'
                              : 'text-ink-faint'
                        }`}
                      >
                        {isCorrect ? <Check className="size-3.5" /> : wasPicked ? <X className="size-3.5" /> : <span className="size-3.5" />}
                        {opt}
                      </div>
                    );
                  })}
                </div>
                {g?.explanation ? (
                  <p className="mt-1.5 text-xs leading-5 text-ink-muted">{g.explanation}</p>
                ) : null}
              </li>
            );
          })}
        </ol>

        {!r.passed ? (
          <button
            type="button"
            onClick={beginTest}
            disabled={startTest.isPending}
            className="mt-4 flex h-11 w-full items-center justify-center gap-1.5 rounded-md bg-surface-inverse text-sm font-semibold text-ink-inverse transition hover:bg-ink disabled:opacity-50"
          >
            <RotateCcw className="size-4" /> {startTest.isPending ? 'Preparing…' : 'Retake test'}
          </button>
        ) : null}
      </div>
    );
  }

  // --- Overview: subtopics + marks + take-test button ---
  const best = topic?.bestResult ?? null;
  const passed = best?.passed ?? false;
  return (
    <div className="mt-6">
      <SectionTitle icon={ListChecks}>Everything to learn in this topic</SectionTitle>
      <ol className="mt-3 space-y-2">
        {(topic?.subtopics ?? []).map((s, i) => (
          <li key={s.id} className="rounded-md bg-surface-sunken p-3 ring-1 ring-border-subtle">
            <div className="flex items-baseline justify-between gap-3">
              <span className="text-sm font-medium text-ink">
                <span className="text-ink-faint">{i + 1}. </span>
                {s.title}
              </span>
              {s.estimatedMin ? <span className="shrink-0 text-xs text-ink-faint">~{s.estimatedMin} min</span> : null}
            </div>
            {s.description ? (
              <p className="mt-1 text-xs leading-5 text-ink-muted">{s.description}</p>
            ) : null}
          </li>
        ))}
      </ol>

      {best ? (
        <div className="mt-4 flex items-center gap-2 rounded-md bg-surface-sunken p-3 text-sm ring-1 ring-border-subtle">
          <Trophy className={`size-4 ${passed ? 'text-accent-green' : 'text-ink-faint'}`} />
          <span className="text-ink-muted">
            Best score <span className="font-semibold text-ink">{best.percent}%</span>
            {topic && topic.attempts > 1 ? ` · ${topic.attempts} attempts` : ''}
            {passed ? ' · passed' : ` · need ${topic?.passPercent ?? best.maxScore}%`}
          </span>
        </div>
      ) : null}

      <button
        type="button"
        onClick={beginTest}
        disabled={startTest.isPending}
        className="mt-4 flex h-11 w-full items-center justify-center gap-1.5 rounded-md bg-surface-inverse text-sm font-semibold text-ink-inverse transition hover:bg-ink disabled:opacity-50"
      >
        <FileQuestion className="size-4" />
        {startTest.isPending
          ? 'Preparing test…'
          : item.status === 'completed'
            ? 'Retake test'
            : best
              ? 'Retake test'
              : 'Take the test to complete this topic'}
      </button>
      {startTest.isError ? (
        <p className="mt-2 text-xs text-accent-red">Could not start the test. Please try again.</p>
      ) : null}
    </div>
  );
}

function SectionTitle({ icon: Icon, children }: { icon: typeof ListChecks; children: ReactNode }) {
  return (
    <div className="flex items-center gap-1.5 text-xs font-medium text-ink-muted">
      <Icon className="size-4" /> {children}
    </div>
  );
}
