CREATE TABLE `CareerChatMessage` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `role` VARCHAR(16) NOT NULL,
  `kind` VARCHAR(24) NOT NULL DEFAULT 'text',
  `body` TEXT NOT NULL,
  `sessionId` VARCHAR(191) NULL,
  `enrolled` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
