CREATE TABLE `MentorBooking` (
  `id` VARCHAR(191) NOT NULL,
  `slotId` VARCHAR(191) NOT NULL,
  `mentorId` VARCHAR(191) NOT NULL,
  `studentId` VARCHAR(191) NOT NULL,
  `topic` VARCHAR(200) NOT NULL,
  `note` VARCHAR(1000) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'confirmed',
  `startsAt` DATETIME(3) NOT NULL,
  `endsAt` DATETIME(3) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
