import type { ReactNode } from 'react';
import {
  Activity,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  Boxes,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  Clapperboard,
  ClipboardCheck,
  Clock,
  Cloud,
  Code2,
  Compass,
  CreditCard,
  Database,
  DollarSign,
  Facebook,
  FileText,
  Flag,
  Flame,
  Folder,
  Gauge,
  Gift,
  Github,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Inbox,
  Info,
  Instagram,
  Key,
  Layers,
  LifeBuoy,
  LineChart,
  Link2,
  Linkedin,
  ListChecks,
  ListTodo,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Mic,
  Network,
  Newspaper,
  PieChart,
  Radio,
  Receipt,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Square,
  SquareCode,
  Star,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  Video,
  Wallet,
  Wand2,
  Wrench,
  Youtube,
  Zap,
} from 'lucide-react';

/**
 * Single source of truth for module icons. The sidebar renders a module's `icon`
 * (a Lucide name) via this map, and the admin module form offers exactly these names
 * — so admins can only pick icons the app can actually display. Add new icons here
 * and they appear in both places automatically.
 */
export const MODULE_ICONS: Record<string, ReactNode> = {
  // Core / navigation
  Home: <Home />,
  Compass: <Compass />,
  Boxes: <Boxes />,
  Layers: <Layers />,
  Folder: <Folder />,
  Info: <Info />,
  Settings: <Settings />,
  // Learning
  GraduationCap: <GraduationCap />,
  BookOpen: <BookOpen />,
  Bookmark: <Bookmark />,
  ClipboardCheck: <ClipboardCheck />,
  ListChecks: <ListChecks />,
  ListTodo: <ListTodo />,
  Code2: <Code2 />,
  SquareCode: <SquareCode />,
  Target: <Target />,
  Trophy: <Trophy />,
  Award: <Award />,
  Rocket: <Rocket />,
  Sparkles: <Sparkles />,
  Flame: <Flame />,
  // People / community
  UserRound: <UserRound />,
  Users: <Users />,
  UserPlus: <UserPlus />,
  UserCheck: <UserCheck />,
  MessageSquare: <MessageSquare />,
  MessagesSquare: <MessagesSquare />,
  Bell: <Bell />,
  Heart: <Heart />,
  Flag: <Flag />,
  // Live / media
  Radio: <Radio />,
  Video: <Video />,
  Mic: <Mic />,
  Camera: <Camera />,
  Clapperboard: <Clapperboard />,
  Headphones: <Headphones />,
  // Scheduling
  Calendar: <Calendar />,
  CalendarDays: <CalendarDays />,
  Clock: <Clock />,
  // Marketing / channels
  Megaphone: <Megaphone />,
  Mail: <Mail />,
  Send: <Send />,
  Inbox: <Inbox />,
  Share2: <Share2 />,
  Link2: <Link2 />,
  Globe: <Globe />,
  Newspaper: <Newspaper />,
  Tag: <Tag />,
  Gift: <Gift />,
  Linkedin: <Linkedin />,
  Facebook: <Facebook />,
  Instagram: <Instagram />,
  Youtube: <Youtube />,
  Github: <Github />,
  // Analytics
  LineChart: <LineChart />,
  BarChart3: <BarChart3 />,
  PieChart: <PieChart />,
  TrendingUp: <TrendingUp />,
  Activity: <Activity />,
  Gauge: <Gauge />,
  // Commerce / finance
  CreditCard: <CreditCard />,
  Wallet: <Wallet />,
  DollarSign: <DollarSign />,
  Receipt: <Receipt />,
  ShoppingBag: <ShoppingBag />,
  // Work / org
  Briefcase: <Briefcase />,
  Building2: <Building2 />,
  Map: <Map />,
  MapPin: <MapPin />,
  Star: <Star />,
  // System / admin
  ShieldCheck: <ShieldCheck />,
  Lock: <Lock />,
  Key: <Key />,
  Database: <Database />,
  Server: <Server />,
  Cloud: <Cloud />,
  Network: <Network />,
  Wand2: <Wand2 />,
  Wrench: <Wrench />,
  Zap: <Zap />,
  Search: <Search />,
  FileText: <FileText />,
  LifeBuoy: <LifeBuoy />,
};

/** All selectable icon names (sorted) — used by the admin module form. */
export const MODULE_ICON_NAMES = Object.keys(MODULE_ICONS).sort();

/** Render a module's icon by name, falling back to a neutral square. */
export function moduleIcon(name: string | null): ReactNode {
  return (name && MODULE_ICONS[name]) || <Square />;
}
